### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by mpryvkin**

### CODE REVIEW

**Comment by pixelliquid** [comment]
Thanks for your pull request mpryvkin. The last changes on the code - all images in one place - got overlooked on the favicon. The class is indeed obsolete, we'll remove that one. But in reaction on the logotype Tools for Research wants to have a fixed path because of the template dependence. We had a internal discussion about this as we know variables are more friendly when making changes to a template. But we really like to have a bit of brand-awareness. The free version has our logo, the premium version has a different approach to putting logos in the brandable template.

**Comment by mpryvkin** [comment]
I understand about the brand awareness, but not everyone installs Limesurvey in root folder. I didn't see your logo on the sample survey until I replaced hard-coded path `/upload/templates/tfr-responsive/images/tfr.png` with `{TEMPLATEURL}images/tfr.png`. 

I appreciate you releasing the template, but the logo would be the first thing to remove if I wanted to use this template for a survey. I believe the reference in the footer is enough.

Also, it would be great to give some credit for [BootstrapForLimeSurvey](https://github.com/mofog/BootstrapForLimeSurvey) to its author, if you used it as a starting point.

**Comment by tammoterhark** [comment]
You are right, we will remove the logo in the header, the one in de footer will do. We will also add credits to mofog, https://github.com/mofog/BootstrapForLimeSurvey. By the way, nearly all code has been altered, but he did inspire us.

**Comment by mpryvkin** [comment]
That makes sense, thanks!

**Pull request closed without merging**
